const COMMON_LANG = {
  pt: {
    calculator: "Cristais Divino",
    tables: "Tabelas Cristais Divino",
    recipes: "Receitas",
    chest: "Puzzle",
    boost: "Boost",
    boostSubtitle: "Calcule cristais de boost e custo em ฿ do +0 ao +16 (pity maximo).",
    boostLevelTitle: "Nivel de Boost",
    boostCurrent: "Boost atual",
    boostTarget: "Boost alvo",
    boostCrystalPriceTitle: "Cristais de Boost (฿)",
    boostInventoryTitle: "Cristais no inventario (abater)",
    boostCrystalSky: "Cristal do Ceu",
    boostCrystalSage: "Cristal do Sabio",
    boostCrystalCrimson: "Cristal Carmesim",
    boostCrystalRadiant: "Cristal Radiante",
    boostPriceSkyTitle: "Preco unitario do Cristal do Ceu",
    boostPriceSageTitle: "Preco unitario do Cristal do Sabio",
    boostPriceCrimsonTitle: "Preco unitario do Cristal Carmesim",
    boostPriceRadiantTitle: "Preco unitario do Cristal Radiante",
    boostItemsTitle: "Itens",
    boostItemSpecialWeaponBase: "Arma especial",
    boostItemIcon: "Icone",
    boostItemType: "Item",
    boostVariant: "Variante",
    boostImportCurrent: "Importar calculadora",
    boostImportProfile: "Importar perfil",
    boostSelectProfilePlaceholder: "Escolha um perfil",
    boostNoProfileSelected: "Selecione um perfil para importar",
    boostNoItemsToImport: "Nenhum item encontrado para importar",
    boostProfileSelectTitle: "Selecione um perfil para importar",
    boostClearItems: "Limpar itens",
    boostFullSetTitle: "Preenche 1 item em cada categoria base",
    boostClearItemsTitle: "Zera todas as quantidades de itens",
    boostPityTitle: "Consumo Maximo (pity)",
    boostTableLevel: "Boost",
    boostTableCrystal: "Cristal",
    boostTableChances: "Chances (%)",
    boostTableAttempts: "Tentativas (pity)",
    boostTablePity: "Cristais maximos",
    boostTableBerriesCost: "฿ por nivel (2/4 cristais)",
    boostCrystals2slot: "2 cristais",
    boostCrystals4slot: "4 cristais",
    boostTotal: "Total:",
    boostCost: "Custo:",
    boostCrystalsUnit: "cristais",
    boostNoRows: "Escolha um alvo maior que o boost atual para ver os calculos.",
    xpTab: "Calculadora XP",
    xpSubtitle: "Calcule quantas poções de XP são necessárias para atingir o nível desejado.",
    xpTierTitle: "Tier do Personagem",
    xpInputTitle: "Dados Atuais",
    xpCurrentLevel: "Nível atual",
    xpCurrentPercent: "XP atual (%)",
    xpTargetLevel: "Nível desejado",
    xpResultTitle: "Poções Necessárias",
    xpTierBronze: "Bronze",
    xpTierSilver: "Prata",
    xpTierGold: "Ouro",
    xpTierDiamond: "Diamante",
    xpPotSmall: "Poção Pequena",
    xpPotMedium: "Poção Média",
    xpPotLarge: "Poção Grande",
    xpMissingXp: "XP faltante",
    xpNoPotsNeeded: "Nenhuma poção necessária",
    xpErrorInvalid: "Dados inválidos",
    charactersTab: "Personagens",
    charactersSubtitle: "Ative personagens, ajuste nível, estrelas e tier, e salve junto do build.",
    charactersSearchLabel: "Pesquisar",
    charactersSearchPlaceholder: "Nome, alias, faccao ou classe",
    charactersRoleFilter: "Classe",
    charactersTierFilter: "Tier",
    charactersFactionFilter: "Faccao",
    charactersMechanicsFilter: "Mecanica",
    charactersGroupTank: "Tank",
    charactersGroupBruiser: "Bruiser",
    charactersGroupDps: "DPS",
    charactersGroupSupport: "Support",
    charactersGroupFighter: "Fighter",
    charactersGroupShooter: "Shooter",
    charactersGroupSlasher: "Slasher",
    charactersGroupSpecialist: "Specialist",
    charactersGroupMarine: "Marinha",
    charactersGroupSupernova: "Supernova",
    charactersGroupDevilFruit: "Fruta do Diabo",
    charactersGroupShichibukai: "Shichibukai",
    charactersGroupRoyalty: "Realeza",
    charactersGroupStrawHat: "Chapeu de Palha",
    charactersMechanicAttackReduction: "Reducao de ataque",
    charactersMechanicAttackInvul: "Ataque com invul",
    charactersMechanicAttackBuff: "Buff de ataque",
    charactersMechanicDefenseBreak: "Quebra defesa",
    charactersMechanicBridgeCreate: "Cria ponte",
    charactersMechanicWallBreak: "Quebra parede",
    charactersMaxLevelFilter: "Status de nível",
    charactersSortFilter: "Classificar por",
    charactersSortNameAZ: "Nome (A-Z)",
    charactersSortLevelDesc: "Nível (maior)",
    charactersSortLevelAsc: "Nível (menor)",
    charactersFilterAll: "Todas",
    charactersOnlyMaxed: "Só 140",
    charactersOnlyNotMaxed: "Ainda não 140",
    charactersSummary: "{unlocked} desbloqueados de {total} | Níveis: {levels} | Estrelas: {starsPoints}",
    charactersNoResults: "Nenhum personagem encontrado com esses filtros.",
    charactersLevel: "Nível",
    charactersStars: "Estrelas",
    charactersTier: "Tier",
    charactersSkin: "Skin",
    charactersSkinBase: "Base",
    charactersSkinLocked: "Bloqueada",
    charactersSkinUnlocked: "Desbloqueada",
    charactersSkinUnlock: "Desbloquear skin",
    charactersSkinLock: "Bloquear skin",
    charactersNoExtraSkins: "Sem skins extras",
    charactersFactions: "Faccoes",
    charactersNoFactions: "Sem faccao mapeada",
    charactersSkinsSoon: "Skins em breve.",
    charactersOpenMenu: "Abrir configurações do personagem",
    charactersSetStars: "Definir {n} estrela(s)",
    charactersActive: "Liberado",
    charactersInactive: "Bloqueado",
    charactersStarsSuffix: "★",
    charactersRoleMelee: "Melee",
    charactersRoleRanged: "Ranged",
    charactersRoleTank: "Tank",
    charactersRoleSupport: "Support",
    boatsTab: "Barcos",
    boatsTitle: "Planejador de Barcos",
    boatsSubtitle: "Marque o que quer construir para ver materiais base, refino, construcao e custo.",
    boatsArsenalTitle: "Arsenal (Lv 6)",
    boatsArsenalHint: "Marque os equipamentos desejados.",
    boatsSkinsTitle: "Skins do Barco",
    boatsSkinsHint: "Tintas nao sao compraveis na loja.",
    boatsSummaryTitle: "Passo a passo",
    boatsSelectAll: "Selecionar todos",
    boatsClearAll: "Limpar",
    boatsNoSelection: "Selecione itens do arsenal ou skins para calcular.",
    boatsStepBuy: "Comprar materiais base",
    boatsStepRefine: "Refino necessario",
    boatsStepBuild: "Construir arsenal",
    boatsStepSkins: "Skins e tintas",
    boatsTotalBaseCost: "Custo total base",
    boatsNotPurchasable: "Nao compravel",
    boatsNoRefineNeeded: "Nenhum refino necessario.",
    boatsNoBuildNeeded: "Nenhuma construcao necessaria.",
    wantedTab: "Wanted Pirates",
    wantedTitle: "Wanted Pirates",
    wantedSearchLabel: "Pesquisar Wanted Pirate",
    wantedSearchPlaceholder: "Digite o nome do Wanted Pirate",
    wantedPirateColumn: "Wanted Pirate",
    wantedOptionColumn: "Opcao",
    wantedSortLabel: "Ordenacao",
    wantedSortAZ: "A-Z",
    wantedSortOriginal: "Original",
    wantedNoResults: "Nenhum Wanted Pirate encontrado.",
    wantedCredits: "Creditos ao ThePlayerLost pelas match-ups",
    wantedSubtabMatchups: "Match-ups",
    wantedSubtabTierList: "Tier List",
    wantedSubtabRows: "Wanted em linhas",
    wantedTierTargetLabel: "Wanted",
    wantedTierCurrentCategory: "Categoria ativa",
    wantedTierSearchPlaceholder: "Buscar wanted no pool",
    wantedTierPoolTitle: "Pool de Counters",
    wantedTierClear: "Limpar tiers",
    wantedTierReset: "Resetar lista",
    wantedTierExport: "Salvar imagem",
    wantedRowsAddWantedLabel: "Adicionar Wanted",
    wantedRowsAddWanted: "Adicionar linha",
    wantedRowsClear: "Limpar linhas",
    wantedRowsReset: "Resetar linhas",
    wantedRowsEmpty: "Adicione wanteds para montar sua tier list por linhas.",
    wantedRowsRemoveRow: "Remover linha",
    wantedRowsAlreadyAdded: "Esse wanted ja foi adicionado.",
    wantedTierRowS: "S",
    wantedTierRowA: "A",
    wantedTierRowB: "B",
    wantedTierRowC: "C",
    wantedTierRowD: "D",
    wantedTierExportSuccess: "Imagem da tier list salva!",
    usefulLinksTab: "Links Uteis",
    usefulLinksTitle: "Links Uteis",
    usefulLinksOfficial: "Links Oficiais do GLA",
    usefulLinksCommunity: "Links da Comunidade",
    chestTitle: "Puzzle das 8 Tochas",
    chestMode: "Modo",
    chestModeSolve: "Resolver",
    chestModeSet: "Setar",
    chestSolve: "Resolver",
    chestReset: "Resetar",
    chestRandom: "Aleatório",
    chestTorchLabel: "Tocha",
    chestNoSolution: "Nenhuma solução encontrada.",
    chestAlreadySolved: "O puzzle já está resolvido.",
    chestStepsTitle: "Passos para resolver:",
    chestStep: "Passo",
    chestClickTorch: "Clique na tocha",
    addItem: "Adicionar item",
    fullSet: "Set completo",
    saveProfile: "Salvar perfil",
    shareBuild: "Compartilhar",
    clear: "Limpar",
    singleStat: "Stat único",
    totalCrystals: "Cristais totais necessários",
    recommended: "Recomendado",
    minimum: "Mínimo",
    maximum: "Máximo",
    language: "Idioma",
    menu: "Menu",
    title: "Labophase",
    hat: "Chapéu",
    shirt: "Camisa",
    pants: "Calça",
    weapon: "Arma",
    necklace: "Colar",
    emblem: "Emblema",
    ring: "Anel",
    accessory: "Acessório",
    requiresCrystals: "Requer {n} cristais",
    saveProfileSuccess: "Perfil salvo!",
    shareBuildCopied: "Link copiado para área de transferência!",
    shareBuildPrompt: "Copie este link:",
    selectProfile: "Selecione um perfil",
    noProfiles: "Nenhum perfil encontrado",
    profileNamePrompt: "Nome do perfil:",
    profileExistsConfirm: "Perfil '{name}' já existe. Sobrescrever?",
    profileCreated: "Perfil criado!",
    profileDeleted: "Perfil excluído!",
    createGroup: "Criar grupo",
    groupDefaultName: "Novo grupo",
    groupColor: "Cor do grupo",
    groupColorBorder: "Cor da borda",
    groupColorBg: "Cor do fundo",
    groupColorTitle: "Cor do título",
    groupColorHeader: "Cor do cabeçalho",
    minimizeGroup: "Minimizar/expandir grupo",
    deleteGroup: "Excluir grupo",
    deleteProfile: "Excluir perfil",
    newProfile: "Novo perfil",
    exportBuild: "Exportar build",
    importBuild: "Importar build",
    exportBuildSuccess: "Build exportado!",
    importBuildSuccess: "Build importado!",
    importBuildError: "Falha ao importar build",
    comboGood: "✔ Stats combinados",
    comboBad: "✖ Stats não combinam",
    comboTableTitle: "Combinações de stats",
    selectVariant: "Selecionar variante",
    dragGroup: "Arrastar grupo",
    groupCrystals: "{n} cristais",
    rarityThresholdsTitle: "Faixas por raridade",
    rarityLabel: "Raridade",
    rarityWhite: "Branco",
    rarityBlue: "Azul",
    rarityPurple: "Roxo",
    rarityGold: "Dourado",
    comboRuleHint: "Aplica-se somente quando os dois stats precisam da mesma quantidade de cristais para atingir o máximo"
  },

  en: {
    calculator: "Divine Crystals",
    tables: "Divine Crystals Tables",
    recipes: "Recipes",
    chest: "Puzzle",
    boost: "Boost",
    boostSubtitle: "Calculate boost crystals and cost in ฿ from +0 to +16 (max pity).",
    boostLevelTitle: "Boost Level",
    boostCurrent: "Current boost",
    boostTarget: "Target boost",
    boostCrystalPriceTitle: "Boost Crystals (฿)",
    boostInventoryTitle: "Crystals in inventory (subtract)",
    boostCrystalSky: "Sky Crystal",
    boostCrystalSage: "Sage Crystal",
    boostCrystalCrimson: "Crimson Crystal",
    boostCrystalRadiant: "Radiant Crystal",
    boostPriceSkyTitle: "Unit price of Sky Crystal",
    boostPriceSageTitle: "Unit price of Sage Crystal",
    boostPriceCrimsonTitle: "Unit price of Crimson Crystal",
    boostPriceRadiantTitle: "Unit price of Radiant Crystal",
    boostItemsTitle: "Items",
    boostItemSpecialWeaponBase: "Special weapon",
    boostItemIcon: "Icon",
    boostItemType: "Item",
    boostVariant: "Variant",
    boostImportCurrent: "Import calculator",
    boostImportProfile: "Import profile",
    boostSelectProfilePlaceholder: "Choose a profile",
    boostNoProfileSelected: "Select a profile to import",
    boostNoItemsToImport: "No items found to import",
    boostProfileSelectTitle: "Select a profile to import",
    boostClearItems: "Clear items",
    boostFullSetTitle: "Fill 1 item in each base category",
    boostClearItemsTitle: "Reset all item quantities to zero",
    boostPityTitle: "Max Consumption (pity)",
    boostTableLevel: "Boost",
    boostTableCrystal: "Crystal",
    boostTableChances: "Chance (%)",
    boostTableAttempts: "Attempts (pity)",
    boostTablePity: "Max crystals",
    boostTableBerriesCost: "฿ per level (2/4 crystals)",
    boostCrystals2slot: "2 crystals",
    boostCrystals4slot: "4 crystals",
    boostTotal: "Total:",
    boostCost: "Cost:",
    boostCrystalsUnit: "crystals",
    boostNoRows: "Choose a target higher than current boost to see calculations.",
    xpTab: "XP Calculator",
    xpSubtitle: "Calculate how many XP potions are needed to reach the target level.",
    xpTierTitle: "Character Tier",
    xpInputTitle: "Current Data",
    xpCurrentLevel: "Current level",
    xpCurrentPercent: "Current XP (%)",
    xpTargetLevel: "Target level",
    xpResultTitle: "Required Potions",
    xpTierBronze: "Bronze",
    xpTierSilver: "Silver",
    xpTierGold: "Gold",
    xpTierDiamond: "Diamond",
    xpPotSmall: "Small Potion",
    xpPotMedium: "Medium Potion",
    xpPotLarge: "Large Potion",
    xpMissingXp: "Missing XP",
    xpNoPotsNeeded: "No potion needed",
    xpErrorInvalid: "Invalid data",
    charactersTab: "Characters",
    charactersSubtitle: "Activate characters, adjust level, stars and tier, and save them with the build.",
    charactersSearchLabel: "Search",
    charactersSearchPlaceholder: "Name, alias, faction or class",
    charactersRoleFilter: "Class",
    charactersTierFilter: "Tier",
    charactersFactionFilter: "Faction",
    charactersMechanicsFilter: "Mechanic",
    charactersGroupTank: "Tank",
    charactersGroupBruiser: "Bruiser",
    charactersGroupDps: "DPS",
    charactersGroupSupport: "Support",
    charactersGroupFighter: "Fighter",
    charactersGroupShooter: "Shooter",
    charactersGroupSlasher: "Slasher",
    charactersGroupSpecialist: "Specialist",
    charactersGroupMarine: "Marine",
    charactersGroupSupernova: "Supernova",
    charactersGroupDevilFruit: "Devil Fruit",
    charactersGroupShichibukai: "Shichibukai",
    charactersGroupRoyalty: "Royalty",
    charactersGroupStrawHat: "Straw Hat",
    charactersMechanicAttackReduction: "Attack reduction",
    charactersMechanicAttackInvul: "Attack with invul",
    charactersMechanicAttackBuff: "Attack buff",
    charactersMechanicDefenseBreak: "Defense break",
    charactersMechanicBridgeCreate: "Create bridge",
    charactersMechanicWallBreak: "Break wall",
    charactersMaxLevelFilter: "Level status",
    charactersSortFilter: "Sort by",
    charactersSortNameAZ: "Name (A-Z)",
    charactersSortLevelDesc: "Level (highest)",
    charactersSortLevelAsc: "Level (lowest)",
    charactersFilterAll: "All",
    charactersOnlyMaxed: "Only 140",
    charactersOnlyNotMaxed: "Not 140 yet",
    charactersSummary: "{unlocked} unlocked of {total} | Levels: {levels} | Stars: {starsPoints}",
    charactersNoResults: "No characters found with these filters.",
    charactersLevel: "Level",
    charactersStars: "Stars",
    charactersTier: "Tier",
    charactersSkin: "Skin",
    charactersSkinBase: "Base",
    charactersSkinLocked: "Locked",
    charactersSkinUnlocked: "Unlocked",
    charactersSkinUnlock: "Unlock skin",
    charactersSkinLock: "Lock skin",
    charactersNoExtraSkins: "No extra skins",
    charactersFactions: "Factions",
    charactersNoFactions: "No mapped faction",
    charactersSkinsSoon: "Skins coming soon.",
    charactersOpenMenu: "Open character settings",
    charactersSetStars: "Set {n} star(s)",
    charactersActive: "Unlocked",
    charactersInactive: "Locked",
    charactersStarsSuffix: "★",
    charactersRoleMelee: "Melee",
    charactersRoleRanged: "Ranged",
    charactersRoleTank: "Tank",
    charactersRoleSupport: "Support",
    boatsTab: "Boats",
    boatsTitle: "Boat Planner",
    boatsSubtitle: "Select what you want to craft to see base materials, refining, build steps and berries cost.",
    boatsArsenalTitle: "Arsenal (Lv 6)",
    boatsArsenalHint: "Select the equipment you want to build.",
    boatsSkinsTitle: "Ship Skins",
    boatsSkinsHint: "Inks are not purchasable in shop.",
    boatsSummaryTitle: "Step by step",
    boatsSelectAll: "Select all",
    boatsClearAll: "Clear",
    boatsNoSelection: "Select arsenal items or skins to calculate.",
    boatsStepBuy: "Buy base materials",
    boatsStepRefine: "Required refining",
    boatsStepBuild: "Build arsenal",
    boatsStepSkins: "Skins and inks",
    boatsTotalBaseCost: "Total base cost",
    boatsNotPurchasable: "Not purchasable",
    boatsNoRefineNeeded: "No refining required.",
    boatsNoBuildNeeded: "No construction required.",
    wantedTab: "Wanted Pirates",
    wantedTitle: "Wanted Pirates",
    wantedSearchLabel: "Search Wanted Pirate",
    wantedSearchPlaceholder: "Type the Wanted Pirate name",
    wantedPirateColumn: "Wanted Pirate",
    wantedOptionColumn: "Option",
    wantedSortLabel: "Sort",
    wantedSortAZ: "A-Z",
    wantedSortOriginal: "Original",
    wantedNoResults: "No Wanted Pirate found.",
    wantedCredits: "Credits to ThePlayerLost for the match-ups",
    wantedSubtabMatchups: "Match-ups",
    wantedSubtabTierList: "Tier List",
    wantedSubtabRows: "Wanted by rows",
    wantedTierTargetLabel: "Wanted",
    wantedTierCurrentCategory: "Active category",
    wantedTierSearchPlaceholder: "Search wanted in pool",
    wantedTierPoolTitle: "Counter pool",
    wantedTierClear: "Clear tiers",
    wantedTierReset: "Reset list",
    wantedTierExport: "Save image",
    wantedRowsAddWantedLabel: "Add Wanted",
    wantedRowsAddWanted: "Add row",
    wantedRowsClear: "Clear rows",
    wantedRowsReset: "Reset rows",
    wantedRowsEmpty: "Add wanted pirates to build your row-based tier list.",
    wantedRowsRemoveRow: "Remove row",
    wantedRowsAlreadyAdded: "This wanted is already added.",
    wantedTierRowS: "S",
    wantedTierRowA: "A",
    wantedTierRowB: "B",
    wantedTierRowC: "C",
    wantedTierRowD: "D",
    wantedTierExportSuccess: "Tier list image saved!",
    usefulLinksTab: "Useful Links",
    usefulLinksTitle: "Useful Links",
    usefulLinksOfficial: "Official GLA Links",
    usefulLinksCommunity: "Community Links",
    chestTitle: "8-Torch Puzzle",
    chestMode: "Mode",
    chestModeSolve: "Solve",
    chestModeSet: "Set",
    chestSolve: "Solve",
    chestReset: "Reset",
    chestRandom: "Random",
    chestTorchLabel: "Torch",
    chestNoSolution: "No solution found.",
    chestAlreadySolved: "Puzzle is already solved.",
    chestStepsTitle: "Steps to solve:",
    chestStep: "Step",
    chestClickTorch: "Click torch",
    addItem: "Add item",
    fullSet: "Full set",
    saveProfile: "Save profile",
    shareBuild: "Share",
    clear: "Clear",
    singleStat: "Single stat",
    totalCrystals: "Total crystals required",
    recommended: "Recommended",
    minimum: "Minimum",
    maximum: "Maximum",
    language: "Language",
    menu: "Menu",
    title: "Labophase",
    hat: "Hat",
    shirt: "Shirt",
    pants: "Pants",
    weapon: "Weapon",
    necklace: "Necklace",
    emblem: "Emblem",
    ring: "Ring",
    accessory: "Accessory",
    requiresCrystals: "Requires {n} crystals",
    saveProfileSuccess: "Profile saved!",
    shareBuildCopied: "Link copied to clipboard!",
    shareBuildPrompt: "Copy this link:",
    selectProfile: "Select profile",
    noProfiles: "No profiles found",
    profileNamePrompt: "Profile name:",
    profileExistsConfirm: "Profile '{name}' already exists. Overwrite?",
    profileCreated: "Profile created!",
    profileDeleted: "Profile deleted!",
    createGroup: "Create group",
    groupDefaultName: "New group",
    groupColor: "Group color",
    groupColorBorder: "Border color",
    groupColorBg: "Background color",
    groupColorTitle: "Title color",
    groupColorHeader: "Header color",
    minimizeGroup: "Minimize/expand group",
    deleteGroup: "Delete group",
    deleteProfile: "Delete profile",
    newProfile: "New profile",
    exportBuild: "Export build",
    importBuild: "Import build",
    exportBuildSuccess: "Build exported!",
    importBuildSuccess: "Build imported!",
    importBuildError: "Failed to import build",
    comboGood: "✔ Stats match",
    comboBad: "✖ Stats don't match",
    comboTableTitle: "Stat combinations",
    selectVariant: "Select variant",
    dragGroup: "Drag group",
    groupCrystals: "{n} crystals",
    rarityThresholdsTitle: "Rarity ranges",
    rarityLabel: "Rarity",
    rarityWhite: "White",
    rarityBlue: "Blue",
    rarityPurple: "Purple",
    rarityGold: "Gold",
    comboRuleHint: "Applies only when both stats need the same number of crystals to reach maximum"
  },

  es: {
    calculator: "Cristales Divinos",
    tables: "Tablas de Cristales Divinos",
    recipes: "Recetas",
    chest: "Puzzle",
    boost: "Boost",
    boostSubtitle: "Calcula cristales de boost y costo en ฿ de +0 a +16 (pity maximo).",
    boostLevelTitle: "Nivel de Boost",
    boostCurrent: "Boost actual",
    boostTarget: "Boost objetivo",
    boostCrystalPriceTitle: "Cristales de Boost (฿)",
    boostInventoryTitle: "Cristales en inventario (restar)",
    boostCrystalSky: "Cristal del Cielo",
    boostCrystalSage: "Cristal del Sabio",
    boostCrystalCrimson: "Cristal Carmesi",
    boostCrystalRadiant: "Cristal Radiante",
    boostPriceSkyTitle: "Precio unitario del Cristal del Cielo",
    boostPriceSageTitle: "Precio unitario del Cristal del Sabio",
    boostPriceCrimsonTitle: "Precio unitario del Cristal Carmesi",
    boostPriceRadiantTitle: "Precio unitario del Cristal Radiante",
    boostItemsTitle: "Objetos",
    boostItemSpecialWeaponBase: "Arma especial",
    boostItemIcon: "Icono",
    boostItemType: "Objeto",
    boostVariant: "Variante",
    boostImportCurrent: "Importar calculadora",
    boostImportProfile: "Importar perfil",
    boostSelectProfilePlaceholder: "Elige un perfil",
    boostNoProfileSelected: "Selecciona un perfil para importar",
    boostNoItemsToImport: "No se encontraron objetos para importar",
    boostProfileSelectTitle: "Selecciona un perfil para importar",
    boostClearItems: "Limpiar items",
    boostFullSetTitle: "Rellena 1 objeto en cada categoria base",
    boostClearItemsTitle: "Pone en cero todas las cantidades",
    boostPityTitle: "Consumo Maximo (pity)",
    boostTableLevel: "Boost",
    boostTableCrystal: "Cristal",
    boostTableChances: "Oportunidades (%)",
    boostTableAttempts: "Intentos (pity)",
    boostTablePity: "Cristales maximos",
    boostTableBerriesCost: "฿ por nivel (2/4 cristales)",
    boostCrystals2slot: "2 cristales",
    boostCrystals4slot: "4 cristales",
    boostTotal: "Total:",
    boostCost: "Costo:",
    boostCrystalsUnit: "cristales",
    boostNoRows: "Elige un objetivo mayor que el boost actual para ver calculos.",
    xpTab: "Calculadora XP",
    xpSubtitle: "Calcula cuántas pociones de XP se necesitan para alcanzar el nivel deseado.",
    xpTierTitle: "Tier del Personaje",
    xpInputTitle: "Datos Actuales",
    xpCurrentLevel: "Nivel actual",
    xpCurrentPercent: "XP actual (%)",
    xpTargetLevel: "Nivel deseado",
    xpResultTitle: "Pociones Necesarias",
    xpTierBronze: "Bronce",
    xpTierSilver: "Plata",
    xpTierGold: "Oro",
    xpTierDiamond: "Diamante",
    xpPotSmall: "Poción Pequeña",
    xpPotMedium: "Poción Mediana",
    xpPotLarge: "Poción Grande",
    xpMissingXp: "XP faltante",
    xpNoPotsNeeded: "No se necesita ninguna poción",
    xpErrorInvalid: "Datos inválidos",
    charactersTab: "Personajes",
    charactersSubtitle: "Activa personajes, ajusta nivel, estrellas y tier, y guárdalos junto al build.",
    charactersSearchLabel: "Buscar",
    charactersSearchPlaceholder: "Nombre, alias, faccion o clase",
    charactersRoleFilter: "Clase",
    charactersTierFilter: "Tier",
    charactersFactionFilter: "Faccion",
    charactersMechanicsFilter: "Mecanica",
    charactersGroupTank: "Tank",
    charactersGroupBruiser: "Bruiser",
    charactersGroupDps: "DPS",
    charactersGroupSupport: "Support",
    charactersGroupFighter: "Fighter",
    charactersGroupShooter: "Shooter",
    charactersGroupSlasher: "Slasher",
    charactersGroupSpecialist: "Specialist",
    charactersGroupMarine: "Marina",
    charactersGroupSupernova: "Supernova",
    charactersGroupDevilFruit: "Fruta del Diablo",
    charactersGroupShichibukai: "Shichibukai",
    charactersGroupRoyalty: "Realeza",
    charactersGroupStrawHat: "Sombrero de Paja",
    charactersMechanicAttackReduction: "Reduccion de ataque",
    charactersMechanicAttackInvul: "Ataque con invul",
    charactersMechanicAttackBuff: "Buff de ataque",
    charactersMechanicDefenseBreak: "Quebra defensa",
    charactersMechanicBridgeCreate: "Crear puente",
    charactersMechanicWallBreak: "Quebra pared",
    charactersMaxLevelFilter: "Estado de nivel",
    charactersSortFilter: "Ordenar por",
    charactersSortNameAZ: "Nombre (A-Z)",
    charactersSortLevelDesc: "Nivel (mayor)",
    charactersSortLevelAsc: "Nivel (menor)",
    charactersFilterAll: "Todas",
    charactersOnlyMaxed: "Solo 140",
    charactersOnlyNotMaxed: "Aún no 140",
    charactersSummary: "{unlocked} desbloqueados de {total} | Niveles: {levels} | Estrellas: {starsPoints}",
    charactersNoResults: "No se encontraron personajes con esos filtros.",
    charactersLevel: "Nivel",
    charactersStars: "Estrellas",
    charactersTier: "Tier",
    charactersSkin: "Skin",
    charactersSkinBase: "Base",
    charactersSkinLocked: "Bloqueada",
    charactersSkinUnlocked: "Desbloqueada",
    charactersSkinUnlock: "Desbloquear skin",
    charactersSkinLock: "Bloquear skin",
    charactersNoExtraSkins: "Sin skins extra",
    charactersFactions: "Facciones",
    charactersNoFactions: "Sin faccion mapeada",
    charactersSkinsSoon: "Skins próximamente.",
    charactersOpenMenu: "Abrir configuración del personaje",
    charactersSetStars: "Definir {n} estrella(s)",
    charactersActive: "Desbloqueado",
    charactersInactive: "Bloqueado",
    charactersStarsSuffix: "★",
    charactersRoleMelee: "Melee",
    charactersRoleRanged: "Ranged",
    charactersRoleTank: "Tank",
    charactersRoleSupport: "Support",
    boatsTab: "Barcos",
    boatsTitle: "Planificador de Barcos",
    boatsSubtitle: "Marca lo que quieres construir para ver materiales base, refinado, pasos y costo en berries.",
    boatsArsenalTitle: "Arsenal (Lv 6)",
    boatsArsenalHint: "Marca el equipamiento que deseas construir.",
    boatsSkinsTitle: "Skins del Barco",
    boatsSkinsHint: "Las tintas no son comprables en la tienda.",
    boatsSummaryTitle: "Paso a paso",
    boatsSelectAll: "Seleccionar todo",
    boatsClearAll: "Limpiar",
    boatsNoSelection: "Selecciona items del arsenal o skins para calcular.",
    boatsStepBuy: "Comprar materiales base",
    boatsStepRefine: "Refinado necesario",
    boatsStepBuild: "Construir arsenal",
    boatsStepSkins: "Skins y tintas",
    boatsTotalBaseCost: "Costo total base",
    boatsNotPurchasable: "No comprable",
    boatsNoRefineNeeded: "No se requiere refinado.",
    boatsNoBuildNeeded: "No se requiere construccion.",
    wantedTab: "Wanted Pirates",
    wantedTitle: "Wanted Pirates",
    wantedSearchLabel: "Buscar Wanted Pirate",
    wantedSearchPlaceholder: "Escribe el nombre del Wanted Pirate",
    wantedPirateColumn: "Wanted Pirate",
    wantedOptionColumn: "Opcion",
    wantedSortLabel: "Orden",
    wantedSortAZ: "A-Z",
    wantedSortOriginal: "Original",
    wantedNoResults: "No se encontro ningun Wanted Pirate.",
    wantedCredits: "Creditos a ThePlayerLost por los enfrentamientos",
    wantedSubtabMatchups: "Match-ups",
    wantedSubtabTierList: "Tier List",
    wantedSubtabRows: "Wanted por filas",
    wantedTierTargetLabel: "Wanted",
    wantedTierCurrentCategory: "Categoria activa",
    wantedTierSearchPlaceholder: "Buscar wanted en el pool",
    wantedTierPoolTitle: "Pool de counters",
    wantedTierClear: "Limpiar tiers",
    wantedTierReset: "Reiniciar lista",
    wantedTierExport: "Guardar imagen",
    wantedRowsAddWantedLabel: "Agregar Wanted",
    wantedRowsAddWanted: "Agregar fila",
    wantedRowsClear: "Limpiar filas",
    wantedRowsReset: "Reiniciar filas",
    wantedRowsEmpty: "Agrega wanteds para montar tu tier list por filas.",
    wantedRowsRemoveRow: "Quitar fila",
    wantedRowsAlreadyAdded: "Ese wanted ya fue agregado.",
    wantedTierRowS: "S",
    wantedTierRowA: "A",
    wantedTierRowB: "B",
    wantedTierRowC: "C",
    wantedTierRowD: "D",
    wantedTierExportSuccess: "Imagen de tier list guardada!",
    usefulLinksTab: "Links Utiles",
    usefulLinksTitle: "Links Utiles",
    usefulLinksOfficial: "Links Oficiales de GLA",
    usefulLinksCommunity: "Links de la Comunidad",
    chestTitle: "Puzzle de 8 Antorchas",
    chestMode: "Modo",
    chestModeSolve: "Resolver",
    chestModeSet: "Setear",
    chestSolve: "Resolver",
    chestReset: "Reiniciar",
    chestRandom: "Aleatorio",
    chestTorchLabel: "Antorcha",
    chestNoSolution: "No se encontró solución.",
    chestAlreadySolved: "El puzzle ya está resuelto.",
    chestStepsTitle: "Pasos para resolver:",
    chestStep: "Paso",
    chestClickTorch: "Haz clic en la antorcha",
    addItem: "Añadir objeto",
    fullSet: "Set completo",
    saveProfile: "Guardar perfil",
    shareBuild: "Compartir",
    clear: "Limpiar",
    singleStat: "Stat único",
    totalCrystals: "Cristales necesarios",
    recommended: "Recomendado",
    minimum: "Mínimo",
    maximum: "Máximo",
    language: "Idioma",
    menu: "Menu",
    title: "Labophase",
    hat: "Chapéu",
    shirt: "Camisa",
    pants: "Pantalones",
    weapon: "Arma",
    necklace: "Collar",
    emblem: "Emblema",
    ring: "Anillo",
    accessory: "Accesorio",
    requiresCrystals: "Requiere {n} cristales",
    saveProfileSuccess: "Perfil guardado!",
    shareBuildCopied: "Enlace copiado al portapapeles!",
    shareBuildPrompt: "Copia este enlace:",
    selectProfile: "Seleccionar perfil",
    noProfiles: "No se encontraron perfiles",
    profileNamePrompt: "Nombre del perfil:",
    profileExistsConfirm: "Perfil '{name}' ya existe. ¿Sobrescribir?",
    profileCreated: "Perfil creado!",
    profileDeleted: "Perfil eliminado!",
    createGroup: "Crear grupo",
    groupDefaultName: "Nuevo grupo",
    groupColor: "Color del grupo",
    groupColorBorder: "Color del borde",
    groupColorBg: "Color de fondo",
    groupColorTitle: "Color del título",
    groupColorHeader: "Color del encabezado",
    minimizeGroup: "Minimizar/expandir grupo",
    deleteGroup: "Eliminar grupo",
    deleteProfile: "Eliminar perfil",
    newProfile: "Nuevo perfil",
    exportBuild: "Exportar build",
    importBuild: "Importar build",
    exportBuildSuccess: "Build exportado!",
    importBuildSuccess: "Build importado!",
    importBuildError: "Error al importar build",
    comboGood: "✔ Stats combinados",
    comboBad: "✖ Stats no combinan",
    comboTableTitle: "Combinaciones de stats",
    selectVariant: "Seleccionar variante",
    dragGroup: "Arrastrar grupo",
    groupCrystals: "{n} cristales",
    rarityThresholdsTitle: "Rangos por rareza",
    rarityLabel: "Rareza",
    rarityWhite: "Blanco",
    rarityBlue: "Azul",
    rarityPurple: "Morado",
    rarityGold: "Dorado",
    comboRuleHint: "Se aplica solo cuando ambos stats necesitan la misma cantidad de cristales para llegar al máximo"
  },

  pl: {
    calculator: "Kryształy Boskie",
    tables: "Tabele Kryształów Boskich",
    recipes: "Przepisy",
    chest: "Skrzynka",
    boost: "Boost",
    boostSubtitle: "Oblicz ile krysztalow oraz koszt w ฿ od +0 do +16",
    boostLevelTitle: "Poziom Boost",
    boostCurrent: "Aktualny boost",
    boostTarget: "Docelowy boost",
    boostCrystalPriceTitle: "Krysztaly Boostu (฿)",
    boostInventoryTitle: "Krysztaly w ekwipunku (odjac)",
    boostCrystalSky: "Krysztal Nieba",
    boostCrystalSage: "Krysztal Mędrca",
    boostCrystalCrimson: "Karmazynowy Krysztal",
    boostCrystalRadiant: "Promienny Krysztal",
    boostPriceSkyTitle: "Cena jednostkowa Krysztalu Nieba",
    boostPriceSageTitle: "Cena jednostkowa Krysztalu Mędrca",
    boostPriceCrimsonTitle: "Cena jednostkowa Karmazynowego Krysztalu",
    boostPriceRadiantTitle: "Cena jednostkowa Promiennego Krysztalu",
    boostItemsTitle: "Przedmioty",
    boostItemSpecialWeaponBase: "Specjalna bron",
    boostItemIcon: "Ikona",
    boostItemType: "Przedmiot",
    boostVariant: "Wariant",
    boostImportCurrent: "Importuj kalkulator",
    boostImportProfile: "Importuj profil",
    boostSelectProfilePlaceholder: "Wybierz profil",
    boostNoProfileSelected: "Wybierz profil do importu",
    boostNoItemsToImport: "Brak przedmiotow do importu",
    boostProfileSelectTitle: "Wybierz profil do importu",
    boostClearItems: "Wyczysc przedmioty",
    boostFullSetTitle: "Ustaw 1 przedmiot w kazdej bazowej kategorii",
    boostClearItemsTitle: "Wyzeruj wszystkie przedmioty",
    boostPityTitle: "Maksymalne zuzycie (pity)",
    boostTableLevel: "Boost",
    boostTableCrystal: "Krysztal",
    boostTableChances: "Szanse (%)",
    boostTableAttempts: "Proby (pity)",
    boostTablePity: "Maks. krysztaly",
    boostTableBerriesCost: "฿ za poziom (2/4 krysztaly)",
    boostCrystals2slot: "2 krysztaly",
    boostCrystals4slot: "4 krysztaly",
    boostTotal: "Suma:",
    boostCost: "Koszt:",
    boostCrystalsUnit: "krysztalow",
    boostNoRows: "Wybierz cel wyzszy niz aktualny boost, aby zobaczyc obliczenia.",
    xpTab: "Kalkulator XP",
    xpSubtitle: "Oblicz ile mikstur XP potrzeba, aby osiągnąć docelowy poziom.",
    xpTierTitle: "Tier Postaci",
    xpInputTitle: "Aktualne Dane",
    xpCurrentLevel: "Aktualny poziom",
    xpCurrentPercent: "Aktualne XP (%)",
    xpTargetLevel: "Docelowy poziom",
    xpResultTitle: "Wymagane Mikstury",
    xpTierBronze: "Brąz",
    xpTierSilver: "Srebro",
    xpTierGold: "Złoto",
    xpTierDiamond: "Diament",
    xpPotSmall: "Mała Mikstura",
    xpPotMedium: "Średnia Mikstura",
    xpPotLarge: "Duża Mikstura",
    xpMissingXp: "Brakujące XP",
    xpNoPotsNeeded: "Brak wymaganych mikstur",
    xpErrorInvalid: "Nieprawidłowe dane",
    charactersTab: "Postacie",
    charactersSubtitle: "Aktywuj postacie, ustaw poziom, gwiazdki i tier oraz zapisuj je razem z buildem.",
    charactersSearchLabel: "Szukaj",
    charactersSearchPlaceholder: "Nazwa, alias, frakcja lub klasa",
    charactersRoleFilter: "Klasa",
    charactersTierFilter: "Tier",
    charactersFactionFilter: "Frakcja",
    charactersMechanicsFilter: "Mechanika",
    charactersGroupTank: "Tank",
    charactersGroupBruiser: "Bruiser",
    charactersGroupDps: "DPS",
    charactersGroupSupport: "Support",
    charactersGroupFighter: "Fighter",
    charactersGroupShooter: "Shooter",
    charactersGroupSlasher: "Slasher",
    charactersGroupSpecialist: "Specialist",
    charactersGroupMarine: "Marynarka",
    charactersGroupSupernova: "Supernova",
    charactersGroupDevilFruit: "Owoc Diabla",
    charactersGroupShichibukai: "Shichibukai",
    charactersGroupRoyalty: "Rodzina krolewska",
    charactersGroupStrawHat: "Slomkowi",
    charactersMechanicAttackReduction: "Redukcja ataku",
    charactersMechanicAttackInvul: "Atak z invul",
    charactersMechanicAttackBuff: "Buff ataku",
    charactersMechanicDefenseBreak: "Lamanie obrony",
    charactersMechanicBridgeCreate: "Tworzy most",
    charactersMechanicWallBreak: "Lamie sciane",
    charactersMaxLevelFilter: "Status poziomu",
    charactersSortFilter: "Sortuj według",
    charactersSortNameAZ: "Nazwa (A-Z)",
    charactersSortLevelDesc: "Poziom (najwyższy)",
    charactersSortLevelAsc: "Poziom (najniższy)",
    charactersFilterAll: "Wszystkie",
    charactersOnlyMaxed: "Tylko 140",
    charactersOnlyNotMaxed: "Jeszcze nie 140",
    charactersSummary: "{unlocked} odblokowanych z {total} | Poziomy: {levels} | Gwiazdki: {starsPoints}",
    charactersNoResults: "Nie znaleziono postaci dla tych filtrów.",
    charactersLevel: "Poziom",
    charactersStars: "Gwiazdki",
    charactersTier: "Tier",
    charactersSkin: "Skin",
    charactersSkinBase: "Base",
    charactersSkinLocked: "Zablokowana",
    charactersSkinUnlocked: "Odblokowana",
    charactersSkinUnlock: "Odblokuj skin",
    charactersSkinLock: "Zablokuj skin",
    charactersNoExtraSkins: "Brak dodatkowych skinów",
    charactersFactions: "Frakcje",
    charactersNoFactions: "Brak przypisanej frakcji",
    charactersSkinsSoon: "Skiny wkrótce.",
    charactersOpenMenu: "Otwórz ustawienia postaci",
    charactersSetStars: "Ustaw {n} gwiazdkę/gwiazdek",
    charactersActive: "Odblokowana",
    charactersInactive: "Zablokowana",
    charactersStarsSuffix: "★",
    charactersRoleMelee: "Melee",
    charactersRoleRanged: "Ranged",
    charactersRoleTank: "Tank",
    charactersRoleSupport: "Support",
    boatsTab: "Statki",
    boatsTitle: "Planer Statkow",
    boatsSubtitle: "Wybierz co chcesz zbudowac, aby zobaczyc materialy bazowe, rafinacje, kroki i koszt w berries.",
    boatsArsenalTitle: "Arsenal (Lv 6)",
    boatsArsenalHint: "Wybierz wyposazenie do zbudowania.",
    boatsSkinsTitle: "Skorki Statku",
    boatsSkinsHint: "Tusze nie sa kupowalne w sklepie.",
    boatsSummaryTitle: "Krok po kroku",
    boatsSelectAll: "Zaznacz wszystko",
    boatsClearAll: "Wyczysc",
    boatsNoSelection: "Wybierz elementy arsenalu lub skorki, aby obliczyc.",
    boatsStepBuy: "Kup materialy bazowe",
    boatsStepRefine: "Wymagana rafinacja",
    boatsStepBuild: "Budowa arsenalu",
    boatsStepSkins: "Skorki i tusze",
    boatsTotalBaseCost: "Laczny koszt bazowy",
    boatsNotPurchasable: "Nie do kupienia",
    boatsNoRefineNeeded: "Brak wymaganej rafinacji.",
    boatsNoBuildNeeded: "Brak wymaganej budowy.",
    wantedTab: "Wanted Pirates",
    wantedTitle: "Wanted Pirates",
    wantedSearchLabel: "Szukaj Wanted Pirate",
    wantedSearchPlaceholder: "Wpisz nazwe Wanted Pirate",
    wantedPirateColumn: "Wanted Pirate",
    wantedOptionColumn: "Opcja",
    wantedSortLabel: "Sortowanie",
    wantedSortAZ: "A-Z",
    wantedSortOriginal: "Oryginal",
    wantedNoResults: "Nie znaleziono Wanted Pirate.",
    wantedCredits: "Podziekowania dla ThePlayerLost za zestawienia",
    wantedSubtabMatchups: "Match-ups",
    wantedSubtabTierList: "Tier List",
    wantedSubtabRows: "Wanted w wierszach",
    wantedTierTargetLabel: "Wanted",
    wantedTierCurrentCategory: "Aktywna kategoria",
    wantedTierSearchPlaceholder: "Szukaj wanted w puli",
    wantedTierPoolTitle: "Pula counterow",
    wantedTierClear: "Wyczysc tiery",
    wantedTierReset: "Resetuj liste",
    wantedTierExport: "Zapisz obraz",
    wantedRowsAddWantedLabel: "Dodaj Wanted",
    wantedRowsAddWanted: "Dodaj wiersz",
    wantedRowsClear: "Wyczysc wiersze",
    wantedRowsReset: "Resetuj wiersze",
    wantedRowsEmpty: "Dodaj wanted, aby zbudowac tier liste po wierszach.",
    wantedRowsRemoveRow: "Usun wiersz",
    wantedRowsAlreadyAdded: "Ten wanted jest juz dodany.",
    wantedTierRowS: "S",
    wantedTierRowA: "A",
    wantedTierRowB: "B",
    wantedTierRowC: "C",
    wantedTierRowD: "D",
    wantedTierExportSuccess: "Obraz tier listy zapisany!",
    usefulLinksTab: "Przydatne Linki",
    usefulLinksTitle: "Przydatne Linki",
    usefulLinksOfficial: "Oficjalne Linki GLA",
    usefulLinksCommunity: "Linki Spolecznosci",
    chestTitle: "Puzzle 8 Pochodni",
    chestMode: "Tryb",
    chestModeSolve: "Rozwiązywanie",
    chestModeSet: "Ustawianie",
    chestSolve: "Rozwiąż",
    chestReset: "Resetuj",
    chestRandom: "Losowy",
    chestTorchLabel: "Pochodnia",
    chestNoSolution: "Nie znaleziono rozwiązania.",
    chestAlreadySolved: "Puzzle jest już rozwiązane.",
    chestStepsTitle: "Kroki rozwiązania:",
    chestStep: "Krok",
    chestClickTorch: "Kliknij pochodnię",
    addItem: "Dodaj przedmiot",
    fullSet: "Pełny zestaw",
    saveProfile: "Zapisz profil",
    shareBuild: "Udostępnij",
    clear: "Wyczyść",
    singleStat: "Pojedynczy stat",
    totalCrystals: "Wymagane kryształy",
    recommended: "Zalecane",
    minimum: "Minimum",
    maximum: "Maksimum",
    language: "Język",
    menu: "Menu",
    title: "Labophase",
    hat: "Kapelusz",
    shirt: "Koszula",
    pants: "Spodnie",
    weapon: "Broń",
    necklace: "Naszyjnik",
    emblem: "Emblemat",
    ring: "Pierścień",
    accessory: "Akcesoria",
    requiresCrystals: "Wymaga {n} kryształów",
    saveProfileSuccess: "Profil zapisany!",
    shareBuildCopied: "Link skopiowany do schowka!",
    shareBuildPrompt: "Skopiuj ten link:",
    selectProfile: "Wybierz profil",
    noProfiles: "Brak profili",
    profileNamePrompt: "Nazwa profilu:",
    profileExistsConfirm: "Profil '{name}' już istnieje. Nadpisać?",
    profileCreated: "Profil utworzony!",
    profileDeleted: "Profil usunięty!",
    createGroup: "Utwórz grupę",
    groupDefaultName: "Nowa grupa",
    groupColor: "Kolor grupy",
    groupColorBorder: "Kolor obramowania",
    groupColorBg: "Kolor tła",
    groupColorTitle: "Kolor tytułu",
    groupColorHeader: "Kolor nagłówka",
    minimizeGroup: "Minimalizuj/rozwijaj grupę",
    deleteGroup: "Usuń grupę",
    deleteProfile: "Usuń profil",
    newProfile: "Nowy profil",
    exportBuild: "Eksportuj build",
    importBuild: "Importuj build",
    exportBuildSuccess: "Build wyeksportowany!",
    importBuildSuccess: "Build zaimportowany!",
    importBuildError: "Błąd podczas importu build",
    comboGood: "✔ Staty pasują",
    comboBad: "✖ Staty nie pasują",
    comboTableTitle: "Kombinacje statów",
    selectVariant: "Wybierz wariant",
    dragGroup: "Przeciągnij grupę",
    groupCrystals: "{n} kryształów",
    rarityThresholdsTitle: "Zakresy rzadkości",
    rarityLabel: "Rzadkość",
    rarityWhite: "Biały",
    rarityBlue: "Niebieski",
    rarityPurple: "Fioletowy",
    rarityGold: "Złoty",
    comboRuleHint: "Dotyczy tylko wtedy, gdy oba staty potrzebują tej samej liczby kryształów, aby osiągnąć maksimum"
  }
};

// Detailed localized names for Boats tab (materials, refinery outputs and arsenal pieces)
const boatsNamesLang = {
  low_grade_cotton: { pt: "Algodao simples", en: "Low-grade cotton", es: "Algodon basico", pl: "Niskiej jakosci bawelna" },
  wood_log: { pt: "Tronco de madeira", en: "Wood log", es: "Tronco de madera", pl: "Drewniany kloda" },
  copper_ore: { pt: "Minerio de cobre", en: "Copper ore", es: "Mineral de cobre", pl: "Ruda miedzi" },
  gun_powder: { pt: "Polvora", en: "Gun powder", es: "Polvora", pl: "Proch" },
  cotton: { pt: "Algodao", en: "Cotton", es: "Algodon", pl: "Bawelna" },
  oak_log: { pt: "Tronco de carvalho", en: "Oak log", es: "Tronco de roble", pl: "Debowa kloda" },
  iron_ore: { pt: "Minerio de ferro", en: "Iron ore", es: "Mineral de hierro", pl: "Ruda zelaza" },
  expert_gun_powder: { pt: "Polvora expert", en: "Expert gun powder", es: "Polvora experta", pl: "Ekspercki proch" },
  advanced_cotton: { pt: "Algodao avancado", en: "Advanced cotton", es: "Algodon avanzado", pl: "Zaawansowana bawelna" },
  mahogany_log: { pt: "Tronco de mogno", en: "Mahogany log", es: "Tronco de caoba", pl: "Mahoniowa kloda" },
  mahogany_plank: { pt: "Tabua de mogno", en: "Mahogany plank", es: "Tablon de caoba", pl: "Mahoniowa deska" },
  steel_ore: { pt: "Minerio de aco", en: "Steel ore", es: "Mineral de acero", pl: "Ruda stali" },
  superior_gun_powder: { pt: "Polvora superior", en: "Superior gun powder", es: "Polvora superior", pl: "Wysokiej klasy proch" },
  professional_cotton: { pt: "Algodao profissional", en: "Professional cotton", es: "Algodon profesional", pl: "Profesjonalna bawelna" },
  adam_log: { pt: "Tronco de adam", en: "Adam log", es: "Tronco de adam", pl: "Koda adam" },
  adam_plank: { pt: "Tabua de adam", en: "Adam plank", es: "Tablon de adam", pl: "Deska adam" },
  titanium_ore: { pt: "Minerio de titanio", en: "Titanium ore", es: "Mineral de titanio", pl: "Ruda tytanu" },
  refined_gun_powder: { pt: "Polvora refinada", en: "Refined gun powder", es: "Polvora refinada", pl: "Rafinowany proch" },
  cola: { pt: "Cola", en: "Cola", es: "Cola", pl: "Cola" },
  gun_barrel: { pt: "Cano de arma", en: "Gun barrel", es: "Canon de arma", pl: "Lufa" },
  cannon_ball: { pt: "Bola de canhao", en: "Cannon ball", es: "Bala de canon", pl: "Kula armatnia" },
  big_cola: { pt: "Cola grande", en: "Big cola", es: "Cola grande", pl: "Duza cola" },
  steel_cannon_ball: { pt: "Bola de canhao de aco", en: "Steel cannon ball", es: "Bala de canon de acero", pl: "Stalowa kula armatnia" },
  battery: { pt: "Bateria", en: "Battery", es: "Bateria", pl: "Bateria" },
  flammable_liquid: { pt: "Liquido inflamavel", en: "Flammable liquid", es: "Liquido inflamable", pl: "Latwopalny plyn" },
  air_tank: { pt: "Tanque de ar", en: "Air tank", es: "Tanque de aire", pl: "Zbiornik powietrza" },
  oil_can: { pt: "Lata de oleo", en: "Oil can", es: "Lata de aceite", pl: "Puszka oleju" },
  poison_mushroom: { pt: "Cogumelo venenoso", en: "Poison mushroom", es: "Hongo venenoso", pl: "Trujacy grzyb" },
  superior_gun_barrel: { pt: "Cano de arma superior", en: "Superior gun barrel", es: "Canon de arma superior", pl: "Wysokiej klasy lufa" },
  blueprint: { pt: "Blueprint", en: "Blueprint", es: "Plano", pl: "Blueprint" },
  expert_oil_can: { pt: "Lata de oleo expert", en: "Expert oil can", es: "Lata de aceite experta", pl: "Ekspercka puszka oleju" },
  expert_gun_barrel: { pt: "Cano de arma expert", en: "Expert gun barrel", es: "Canon de arma experto", pl: "Ekspercka lufa" },
  alkaline_battery: { pt: "Bateria alcalina", en: "Alkaline battery", es: "Bateria alcalina", pl: "Bateria alkaliczna" },
  white_ink: { pt: "Tinta branca", en: "White ink", es: "Tinta blanca", pl: "Bialy tusz" },
  black_ink: { pt: "Tinta preta", en: "Black ink", es: "Tinta negra", pl: "Czarny tusz" },
  blue_ink: { pt: "Tinta azul", en: "Blue ink", es: "Tinta azul", pl: "Niebieski tusz" },
  green_ink: { pt: "Tinta verde", en: "Green ink", es: "Tinta verde", pl: "Zielony tusz" },
  purple_ink: { pt: "Tinta roxa", en: "Purple ink", es: "Tinta morada", pl: "Fioletowy tusz" },
  red_ink: { pt: "Tinta vermelha", en: "Red ink", es: "Tinta roja", pl: "Czerwony tusz" },
  yellow_ink: { pt: "Tinta amarela", en: "Yellow ink", es: "Tinta amarilla", pl: "Zolty tusz" },

  wood_planks: { pt: "Tabuas de madeira", en: "Wood planks", es: "Tablones de madera", pl: "Drewniane deski" },
  copper_ingot: { pt: "Barra de cobre", en: "Copper ingot", es: "Lingote de cobre", pl: "Sztabka miedzi" },
  low_grade_cloth: { pt: "Tecido simples", en: "Low-grade cloth", es: "Tela basica", pl: "Niska jakosc tkaniny" },
  low_grade_rope: { pt: "Corda simples", en: "Low-grade rope", es: "Cuerda basica", pl: "Niska jakosc liny" },
  copper_nail: { pt: "Prego de cobre", en: "Copper nail", es: "Clavo de cobre", pl: "Miedziany gwozdz" },
  oak_planks: { pt: "Tabuas de carvalho", en: "Oak planks", es: "Tablones de roble", pl: "Debowe deski" },
  iron_ingot: { pt: "Barra de ferro", en: "Iron ingot", es: "Lingote de hierro", pl: "Sztabka zelaza" },
  cloth: { pt: "Tecido", en: "Cloth", es: "Tela", pl: "Tkanina" },
  rope: { pt: "Corda", en: "Rope", es: "Cuerda", pl: "Lina" },
  iron_nail: { pt: "Prego de ferro", en: "Iron nail", es: "Clavo de hierro", pl: "Zelazny gwozdz" },
  mahogany_planks: { pt: "Tabuas de mogno", en: "Mahogany planks", es: "Tablones de caoba", pl: "Mahoniowe deski" },
  steel_ingot: { pt: "Barra de aco", en: "Steel ingot", es: "Lingote de acero", pl: "Sztabka stali" },
  advanced_cloth: { pt: "Tecido avancado", en: "Advanced cloth", es: "Tela avanzada", pl: "Zaawansowana tkanina" },
  advanced_rope: { pt: "Corda avancada", en: "Advanced rope", es: "Cuerda avanzada", pl: "Zaawansowana lina" },
  steel_nail: { pt: "Prego de aco", en: "Steel nail", es: "Clavo de acero", pl: "Stalowy gwozdz" },
  adam_planks: { pt: "Tabuas de adam", en: "Adam planks", es: "Tablones de adam", pl: "Deski adam" },
  titanium_ingot: { pt: "Barra de titanio", en: "Titanium ingot", es: "Lingote de titanio", pl: "Sztabka tytanu" },
  professional_cloth: { pt: "Tecido profissional", en: "Professional cloth", es: "Tela profesional", pl: "Profesjonalna tkanina" },
  professional_rope: { pt: "Corda profissional", en: "Professional rope", es: "Cuerda profesional", pl: "Profesjonalna lina" },
  titanium_nail: { pt: "Prego de titanio", en: "Titanium nail", es: "Clavo de titanio", pl: "Tytanowy gwozdz" },

  ship_upgrade_kit: { pt: "Kit de upgrade do navio", en: "Ship upgrade kit", es: "Kit de mejora del barco", pl: "Zestaw ulepszenia statku" },
  cannon: { pt: "Canhao", en: "Cannon", es: "Canon", pl: "Armata" },
  sail: { pt: "Vela", en: "Sail", es: "Vela", pl: "Zagiel" },
  hull: { pt: "Casco", en: "Hull", es: "Casco", pl: "Kadlub" },
  fire_cannon: { pt: "Canhao de fogo", en: "Fire cannon", es: "Canon de fuego", pl: "Armata ogniowa" },
  acid_cannon: { pt: "Canhao de acido", en: "Acid cannon", es: "Canon de acido", pl: "Armata kwasowa" },
  shotgun: { pt: "Shotgun", en: "Shotgun", es: "Escopeta", pl: "Shotgun" },
  chain_shot: { pt: "Tiro em corrente", en: "Chain shot", es: "Disparo en cadena", pl: "Lancuchowy strzal" },
  ram: { pt: "Ariete", en: "Ram", es: "Ariete", pl: "Taran" },
  machine_gun: { pt: "Metralhadora", en: "Machine gun", es: "Ametralladora", pl: "Karabin maszynowy" },
  speed_up: { pt: "Aumento de velocidade", en: "Speed up", es: "Aumento de velocidad", pl: "Przyspieszenie" },
  heavy_cannon: { pt: "Canhao pesado", en: "Heavy cannon", es: "Canon pesado", pl: "Ciezka armata" },
  explosive_barrel: { pt: "Barril explosivo", en: "Explosive barrel", es: "Barril explosivo", pl: "Wybuchowa beczka" },
  oil_barrel: { pt: "Barril de oleo", en: "Oil barrel", es: "Barril de aceite", pl: "Beczka oleju" },
  speed_burst: { pt: "Rajada de velocidade", en: "Speed burst", es: "Rafaga de velocidad", pl: "Zryw predkosci" },
  armor_up: { pt: "Aumento de armadura", en: "Armor up", es: "Aumento de armadura", pl: "Wzmocnienie pancerza" },
  poison_bomb: { pt: "Bomba de veneno", en: "Poison bomb", es: "Bomba venenosa", pl: "Trujaca bomba" },
  flamethrower: { pt: "Lanca-chamas", en: "Flamethrower", es: "Lanzallamas", pl: "Miotacz ognia" },
  bombardier: { pt: "Bombardeiro", en: "Bombardier", es: "Bombardero", pl: "Bombardier" },
  bubble: { pt: "Bolha", en: "Bubble", es: "Burbuja", pl: "Babel" },
  sonar: { pt: "Sonar", en: "Sonar", es: "Sonar", pl: "Sonar" },
  smoke_bomb: { pt: "Bomba de fumaca", en: "Smoke bomb", es: "Bomba de humo", pl: "Bomba dymna" },
  call_reinforcement: { pt: "Chamar reforco", en: "Call reinforcement", es: "Llamar refuerzo", pl: "Wezwij wsparcie" },
  dive: { pt: "Mergulho", en: "Dive", es: "Buceo", pl: "Nurkowanie" },
  coup_do_burst: { pt: "Coup do Burst", en: "Coup do Burst", es: "Coup do Burst", pl: "Coup do Burst" },
  mortar: { pt: "Morteiro", en: "Mortar", es: "Mortero", pl: "Mozdzierz" },
  reflect: { pt: "Refletir", en: "Reflect", es: "Reflejar", pl: "Odbicie" },

  blanco: { pt: "Blanco", en: "Blanco", es: "Blanco", pl: "Blanco" },
  ashes: { pt: "Ashes", en: "Ashes", es: "Ashes", pl: "Ashes" },
  quartz: { pt: "Quartz", en: "Quartz", es: "Quartz", pl: "Quartz" },
  topaz: { pt: "Topaz", en: "Topaz", es: "Topaz", pl: "Topaz" },
  ruby: { pt: "Ruby", en: "Ruby", es: "Ruby", pl: "Ruby" },
  sapphire: { pt: "Sapphire", en: "Sapphire", es: "Sapphire", pl: "Sapphire" },
  sapphite: { pt: "Sapphite", en: "Sapphite", es: "Sapphite", pl: "Sapphite" },
  emerald: { pt: "Emerald", en: "Emerald", es: "Emerald", pl: "Emerald" },
  pure: { pt: "Pure", en: "Pure", es: "Pure", pl: "Pure" },
  classic: { pt: "Classic", en: "Classic", es: "Classic", pl: "Classic" },
  exotic: { pt: "Exotic", en: "Exotic", es: "Exotic", pl: "Exotic" },
  venomous: { pt: "Venomous", en: "Venomous", es: "Venomous", pl: "Venomous" },
  cursed: { pt: "Cursed", en: "Cursed", es: "Cursed", pl: "Cursed" },
  turquoise: { pt: "Turquoise", en: "Turquoise", es: "Turquoise", pl: "Turquoise" },
  vermillion: { pt: "Vermillion", en: "Vermillion", es: "Vermillion", pl: "Vermillion" },
  carmesin: { pt: "Carmesin", en: "Carmesin", es: "Carmesin", pl: "Carmesin" },
  burly_wood: { pt: "Burly Wood", en: "Burly Wood", es: "Burly Wood", pl: "Burly Wood" },
  chartreuse: { pt: "Chartreuse", en: "Chartreuse", es: "Chartreuse", pl: "Chartreuse" },
  pinky: { pt: "Pinky", en: "Pinky", es: "Pinky", pl: "Pinky" },
  holy: { pt: "Holy", en: "Holy", es: "Holy", pl: "Holy" }
};

// ---- Recipes tab i18n (separate from flat lang object) ----
const RECIPES_LANG = {
  pt: {
    ui: {
      selectRecipe: "Selecione uma Receita",
      qtyLabel: "📦 Quantidade (1\u2013100)",
      unitCostLabel: "\u2699\ufe0f Custo Unit\u00e1rio (por item)",
      totalCostLabel: "\ud83e\udded Custo Total",
      sellPriceLabel: "\ud83d\udcb0 Pre\u00e7o de Venda",
      profitLabel: "\ud83e\udd11 Lucro",
      cookTimeLabel: "\u23f1\ufe0f Tempo de Cozimento",
      bagSlotsLabel: "\ud83c\udf92 Slots na Bag",
      levelLabel: "N\u00edvel",
      secondsSuffix: "s"
    },
    currency: { berry: { symbol: "\u0E3F" } },
    item: {
      premium_raw_beef: "Bife Cru Premium",
      raw_lobster: "Lagosta Crua",
      raw_shrimp: "Camar\u00e3o Cru",
      raw_rabbit_meat: "Carne de Coelho Crua",
      raw_fish: "Peixe Cru",
      tuna: "Atum",
      oyster: "Ostra",
      bacon: "Bacon",
      egg: "Ovo",
      butter: "Manteiga",
      green_leaves: "Folhas Verdes",
      lettuce: "Alface",
      tomatoes: "Tomates",
      lemon: "Lim\u00e3o",
      water: "\u00c1gua",
      white_wine: "Vinho Branco",
      mushroom: "Cogumelo",
      white_truffle: "Trufa Branca",
      salt: "Sal",
      pepper: "Pimenta",
      rice: "Arroz",
      garlic: "Alho",
      potato: "Batata",
      olive_oil: "Azeite",
      onion: "Cebola",
      heavy_cream: "Creme de Leite",
      pasta: "Macarr\u00e3o",
      cheese: "Queijo",
      crab_meat: "Carne de Caranguejo",
      raw_octopus: "Polvo Cru",
      chicken: "Frango",
      raw_lamb_meat: "Carne de Cordeiro Crua"
    },
    recipe: {
      steak_and_egg_skillet: "Bife e Ovo de Frigideira",
      italian_salad: "Salada Italiana",
      meat_medallion: "Medal\u00e3o de Carne",
      gourmet_meat_skewer: "Espetinho de Carne Gourmet",
      rabbit_curry: "Curry de Coelho",
      shrimp_scampi: "Camar\u00e3o ao Scampi",
      oyster_stew: "Ensopado de Ostras",
      seafood_paella: "Paella de Frutos do Mar",
      grilled_tuna: "Atum Grelhado",
      wagyu_beef: "Wagyu",
      octopus_skewer: "Espetinho de Polvo",
      crab_soup: "Sopa de Caranguejo",
      lamb_meat: "Carne de Cordeiro",
      grilled_octopus: "Polvo Grelhado",
      teriyaki_chicken: "Frango Teriyaki",
      shrimp_paella: "Paella de Camar\u00e3o"
    }
  },

  en: {
    ui: {
      selectRecipe: "Select a Recipe",
      qtyLabel: "\ud83d\udce6 Quantity (1\u2013100)",
      unitCostLabel: "\u2699\ufe0f Unit cost (per item)",
      totalCostLabel: "\ud83e\udded Total cost",
      sellPriceLabel: "\ud83d\udcb0 Sell price",
      profitLabel: "\ud83e\udd11 Profit",
      cookTimeLabel: "\u23f1\ufe0f Cook time",
      bagSlotsLabel: "\ud83c\udf92 Bag slots",
      levelLabel: "Level",
      secondsSuffix: "s"
    },
    currency: { berry: { symbol: "\u0E3F" } },
    item: {
      premium_raw_beef: "Premium Raw Beef",
      raw_lobster: "Raw Lobster",
      raw_shrimp: "Raw Shrimp",
      raw_rabbit_meat: "Raw Rabbit Meat",
      raw_fish: "Raw Fish",
      tuna: "Tuna",
      oyster: "Oyster",
      bacon: "Bacon",
      egg: "Egg",
      butter: "Butter",
      green_leaves: "Green Leaves",
      lettuce: "Lettuce",
      tomatoes: "Tomatoes",
      lemon: "Lemon",
      water: "Water",
      white_wine: "White Wine",
      mushroom: "Mushroom",
      white_truffle: "White Truffle",
      salt: "Salt",
      pepper: "Pepper",
      rice: "Rice",
      garlic: "Garlic",
      potato: "Potato",
      olive_oil: "Olive Oil",
      onion: "Onion",
      heavy_cream: "Heavy Cream",
      pasta: "Pasta",
      cheese: "Cheese",
      crab_meat: "Crab Meat",
      raw_octopus: "Raw Octopus",
      chicken: "Chicken",
      raw_lamb_meat: "Raw Lamb Meat"
    },
    recipe: {
      steak_and_egg_skillet: "Steak and Egg Skillet",
      italian_salad: "Italian Salad",
      meat_medallion: "Meat Medallion",
      gourmet_meat_skewer: "Gourmet Meat Skewer",
      rabbit_curry: "Rabbit Curry",
      shrimp_scampi: "Shrimp Scampi",
      oyster_stew: "Oyster Stew",
      seafood_paella: "Seafood Paella",
      grilled_tuna: "Grilled Tuna",
      wagyu_beef: "Wagyu",
      octopus_skewer: "Octopus Skewer",
      crab_soup: "Crab Soup",
      lamb_meat: "Lamb Meat",
      grilled_octopus: "Grilled Octopus",
      teriyaki_chicken: "Teriyaki Chicken",
      shrimp_paella: "Shrimp Paella"
    }
  },

  es: {
    ui: {
      selectRecipe: "Seleccionar una Receta",
      qtyLabel: "\ud83d\udce6 Cantidad (1\u2013100)",
      unitCostLabel: "\u2699\ufe0f Costo unitario (por \u00edtem)",
      totalCostLabel: "\ud83e\udded Costo total",
      sellPriceLabel: "\ud83d\udcb0 Precio de venta",
      profitLabel: "\ud83e\udd11 Ganancia",
      cookTimeLabel: "\u23f1\ufe0f Tiempo de cocci\u00f3n",
      bagSlotsLabel: "\ud83c\udf92 Ranuras de bolsa",
      levelLabel: "Nivel",
      secondsSuffix: "s"
    },
    currency: { berry: { symbol: "\u0E3F" } },
    item: {
      premium_raw_beef: "Carne de Res Premium Cruda",
      raw_lobster: "Langosta Cruda",
      raw_shrimp: "Camar\u00f3n Crudo",
      raw_rabbit_meat: "Carne de Conejo Cruda",
      raw_fish: "Pescado Crudo",
      tuna: "At\u00fan",
      oyster: "Ostra",
      bacon: "Tocino",
      egg: "Huevo",
      butter: "Mantequilla",
      green_leaves: "Hojas Verdes",
      lettuce: "Lechuga",
      tomatoes: "Tomates",
      lemon: "Lim\u00f3n",
      water: "Agua",
      white_wine: "Vino Blanco",
      mushroom: "Champi\u00f1\u00f3n",
      white_truffle: "Trufa Blanca",
      salt: "Sal",
      pepper: "Pimienta",
      rice: "Arroz",
      garlic: "Ajo",
      potato: "Papa",
      olive_oil: "Aceite de Oliva",
      onion: "Cebolla",
      heavy_cream: "Crema Espesa",
      pasta: "Pasta",
      cheese: "Queso",
      crab_meat: "Carne de Cangrejo",
      raw_octopus: "Pulpo Crudo",
      chicken: "Pollo",
      raw_lamb_meat: "Carne de Cordero Cruda"
    },
    recipe: {
      steak_and_egg_skillet: "Sart\u00e9n de Bist\u00e9c y Huevo",
      italian_salad: "Ensalada Italiana",
      meat_medallion: "Medal\u00f3n de Carne",
      gourmet_meat_skewer: "Brocheta de Carne Gourmet",
      rabbit_curry: "Curry de Conejo",
      shrimp_scampi: "Camar\u00f3n al Scampi",
      oyster_stew: "Guiso de Ostras",
      seafood_paella: "Paella de Mariscos",
      grilled_tuna: "At\u00fan a la Parrilla",
      wagyu_beef: "Wagyu",
      octopus_skewer: "Brocheta de Pulpo",
      crab_soup: "Sopa de Cangrejo",
      lamb_meat: "Carne de Cordero",
      grilled_octopus: "Pulpo a la Parrilla",
      teriyaki_chicken: "Pollo Teriyaki",
      shrimp_paella: "Paella de Camarones"
    }
  },

  pl: {
    ui: {
      selectRecipe: "Wybierz przepis",
      qtyLabel: "\ud83d\udce6 Ilo\u015b\u0107 (1\u2013100)",
      unitCostLabel: "\u2699\ufe0f Koszt jednostkowy (za przedmiot)",
      totalCostLabel: "\ud83e\udded Koszt ca\u0142kowity",
      sellPriceLabel: "\ud83d\udcb0 Cena sprzeda\u017cy",
      profitLabel: "\ud83e\udd11 Zysk",
      cookTimeLabel: "\u23f1\ufe0f Czas gotowania",
      bagSlotsLabel: "\ud83c\udf92 Sloty w plecaku",
      levelLabel: "Poziom",
      secondsSuffix: "s"
    },
    currency: { berry: { symbol: "\u0E3F" } },
    item: {
      premium_raw_beef: "Premium Surowa Wo\u0142owina",
      raw_lobster: "Surowy Homar",
      raw_shrimp: "Surowe Krewetki",
      raw_rabbit_meat: "Surowe Mi\u0119so z Kr\u00f3lika",
      raw_fish: "Surowa Ryba",
      tuna: "Tu\u0144czyk",
      oyster: "Ostryga",
      bacon: "Boczek",
      egg: "Jajko",
      butter: "Mas\u0142o",
      green_leaves: "Zielone Li\u015bcie",
      lettuce: "Sa\u0142ata",
      tomatoes: "Pomidory",
      lemon: "Cytryna",
      water: "Woda",
      white_wine: "Bia\u0142e Wino",
      mushroom: "Grzyb",
      white_truffle: "Bia\u0142a Trufla",
      salt: "S\u00f3l",
      pepper: "Pieprz",
      rice: "Ry\u017c",
      garlic: "Czosnek",
      potato: "Ziemniak",
      olive_oil: "Oliwa z Oliwek",
      onion: "Cebula",
      heavy_cream: "\u015amietanka",
      pasta: "Makaron",
      cheese: "Ser",
      crab_meat: "Mi\u0119so Kraba",
      raw_octopus: "Surowa O\u015bmiornica",
      chicken: "Kurczak",
      raw_lamb_meat: "Surowe Mi\u0119so Jagni\u0119ce"
    },
    recipe: {
      steak_and_egg_skillet: "Stek z Jajkiem na Patelni",
      italian_salad: "Sa\u0142atka W\u0142oska",
      meat_medallion: "Medalion z Mi\u0119sa",
      gourmet_meat_skewer: "Szasz\u0142yk z Mi\u0119sa Gourmet",
      rabbit_curry: "Curry z Kr\u00f3lika",
      shrimp_scampi: "Krewetki Scampi",
      oyster_stew: "Gulasz z Ostryg",
      seafood_paella: "Paella z Owocami Morza",
      grilled_tuna: "Grillowany Tu\u0144czyk",
      wagyu_beef: "Wagyu",
      octopus_skewer: "Szasz\u0142yk z O\u015bmiornicy",
      crab_soup: "Zupa z Kraba",
      lamb_meat: "Jagni\u0119cina",
      grilled_octopus: "Grillowana O\u015bmiornica",
      teriyaki_chicken: "Kurczak Teriyaki",
      shrimp_paella: "Paella z Krewetkami"
    }
  }
};

const FALLBACK_LANG = "en";

function isPlainObject(value) {
  return Object.prototype.toString.call(value) === "[object Object]";
}

function mergeLangTree(baseValue, overrideValue) {
  if (Array.isArray(baseValue) || Array.isArray(overrideValue)) {
    return overrideValue !== undefined ? overrideValue : baseValue;
  }

  const baseIsObj = isPlainObject(baseValue);
  const overrideIsObj = isPlainObject(overrideValue);

  if (!baseIsObj && !overrideIsObj) {
    return overrideValue !== undefined ? overrideValue : baseValue;
  }

  const result = {};
  const keys = new Set([
    ...Object.keys(baseIsObj ? baseValue : {}),
    ...Object.keys(overrideIsObj ? overrideValue : {})
  ]);

  keys.forEach((key) => {
    const merged = mergeLangTree(
      baseIsObj ? baseValue[key] : undefined,
      overrideIsObj ? overrideValue[key] : undefined
    );
    if (merged !== undefined) result[key] = merged;
  });

  return result;
}

function buildLanguageBundles(commonByLang, recipesByLang, fallbackLang) {
  const fallbackCommon = commonByLang[fallbackLang] || {};
  const fallbackRecipes = recipesByLang[fallbackLang] || {};
  const codes = new Set([
    ...Object.keys(commonByLang || {}),
    ...Object.keys(recipesByLang || {})
  ]);

  const bundles = {};
  codes.forEach((code) => {
    bundles[code] = {
      common: mergeLangTree(fallbackCommon, commonByLang[code] || {}),
      recipes: mergeLangTree(fallbackRecipes, recipesByLang[code] || {})
    };
  });

  if (!bundles[fallbackLang]) {
    bundles[fallbackLang] = {
      common: mergeLangTree({}, fallbackCommon),
      recipes: mergeLangTree({}, fallbackRecipes)
    };
  }

  return bundles;
}

const LANGUAGE_BUNDLES = buildLanguageBundles(COMMON_LANG, RECIPES_LANG, FALLBACK_LANG);

const lang = {};
const recipesLang = {};

Object.keys(LANGUAGE_BUNDLES).forEach((code) => {
  lang[code] = LANGUAGE_BUNDLES[code].common;
  recipesLang[code] = LANGUAGE_BUNDLES[code].recipes;
});

// Register a new language in one place.
// Example:
// registerLanguage("fr", { common: { menu: "Menu" }, recipes: { ui: { selectRecipe: "Choisir" } } });
function registerLanguage(code, bundle = {}) {
  if (!code) return;
  const normalized = String(code).trim().toLowerCase();
  if (!normalized) return;

  const merged = {
    common: mergeLangTree(lang[FALLBACK_LANG] || {}, bundle.common || {}),
    recipes: mergeLangTree(recipesLang[FALLBACK_LANG] || {}, bundle.recipes || {})
  };

  LANGUAGE_BUNDLES[normalized] = merged;
  lang[normalized] = merged.common;
  recipesLang[normalized] = merged.recipes;
}

const isBrowser = typeof window !== "undefined" && typeof document !== "undefined";
const storage = isBrowser && window.localStorage ? window.localStorage : null;
let currentLang = (storage && storage.getItem("lang")) || "en";
if (!lang[currentLang]) currentLang = FALLBACK_LANG;

// Apply translations immediately on load (only in browser)
if (isBrowser) applyTranslations();

function t(key) {
  const current = lang[currentLang] || lang[FALLBACK_LANG] || {};
  const fallback = lang[FALLBACK_LANG] || {};
  return current[key] || fallback[key] || key;
}

function setLang(l) {
  currentLang = lang[l] ? l : FALLBACK_LANG;
  if (storage) storage.setItem("lang", currentLang);
  if (isBrowser) applyTranslations();
}

function applyTranslations() {
  if (!isBrowser) return;

  document.querySelectorAll("[data-lang]:not(.langBtn)").forEach((el) => {
    const key = el.getAttribute("data-lang");
    el.innerText = t(key);
  });

  document.querySelectorAll("[data-lang-alt]").forEach((el) => {
    const key = el.getAttribute("data-lang-alt");
    el.setAttribute("alt", t(key));
  });

  document.querySelectorAll("[data-lang-title]").forEach((el) => {
    const key = el.getAttribute("data-lang-title");
    el.setAttribute("title", t(key));
  });

  // Update variant names in card headers
  document.querySelectorAll(".card").forEach((card) => {
    const variantCategory = card.getAttribute('data-variant-category');
    const variantId = card.getAttribute('data-variant-id');
    const nameSpan = card.querySelector('.cardHeader b');
    
    if (variantCategory && variantId && items[variantCategory]?.variants[variantId]) {
      nameSpan.textContent = getVariantName(variantCategory, variantId);
    }
  });

  // Sync document title + html lang attribute
  document.title = t("title");
  document.documentElement.lang = currentLang;

  updateLangButtons();

  // Re-render any dynamic content that depends on the current language
  if (typeof gerarTabelas === "function") gerarTabelas();
  if (typeof recalc === "function") recalc();
  if (typeof recipesApplyTranslations === "function") recipesApplyTranslations();
  if (typeof chestApplyTranslations === "function") chestApplyTranslations();
  if (typeof boostRecalc === "function") boostRecalc();
  if (typeof xpBuildTierStars === "function") xpBuildTierStars();
  if (typeof xpRecalc === "function") xpRecalc();
  if (typeof charactersApplyTranslations === "function") charactersApplyTranslations();
  if (typeof boatsApplyTranslations === "function") boatsApplyTranslations();
  if (typeof wantedApplyTranslations === "function") wantedApplyTranslations();
}

function updateLangButtons() {
  document.querySelectorAll(".langBtn").forEach((btn) => {
    if (btn.getAttribute("data-lang") === currentLang) {
      btn.classList.add("active");
    } else {
      btn.classList.remove("active");
    }
  });
}
